# Generated by Django 4.2 on 2024-09-21 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0002_contact'),
        ('inscription', '0002_rename_username_member_nom_remove_member_full_name'),
    ]

    operations = [
    ]
